### ISSUE TITLE
Amazon Fire Stick 4k TV

### ISSUE THREAD

**Issue by phodina** [amonet-kamakiri/kamakiri#6]
Hi,
I'm attempting to use this repo on the Amazon Fire Stick 4k TV.

However, there seems to be an issue when disabling the watchdog.

```
./bootrom-step.sh
[2023-02-24 14:10:12.284836] Waiting for bootrom
[2023-02-24 14:10:14.086785] Found port = /dev/ttyACM0
[2023-02-24 14:10:14.125533] Handshake
[2023-02-24 14:10:14.147052] Disable watchdog
Traceback (most recent call last):
  File "/home/pethod/kamakiri/modules/main.py", line 119, in <module>
    main(dev)
  File "/home/pethod/kamakiri/modules/main.py", line 24, in main
    load_payload(dev)
  File "/home/pethod/kamakiri/modules/load_payload.py", line 47, in load_payload
    dev.write32(0x10007000, 0x22000000)
  File "/home/pethod/kamakiri/modules/common.py", line 147, in write32
    self.check(self.dev.read(2), b'\x00\x01') # arg check
  File "/home/pethod/kamakiri/modules/common.py", line 84, in check
    raise RuntimeError("ERROR: Serial protocol mismatch, expected {} got {}".format(gold.hex(), test.hex()))
RuntimeError: ERROR: Serial protocol mismatch, expected 0001 got 0000
```

**Comment by serv0id** [comment]
Are you sure you have shorted it properly?
